### PR TITLE
Fix all issues left that prevent the CI from succeeding. Run tests on GCC v9 and Clang v8

### PR DESCRIPTION
**Pull request by Kijewski**
Closes: #2.
Closes: #4.

Please see the individual commit messages for further information.

### CODE REVIEW

**Comment by simonask** [comment]
Very nice changes, thanks for that!

Could I ask you to split this PR into those that are purely CI related and those changes you believe to be bugfixes? Some of those I'm not 100% sure about yet, and I would like to merge the CI stuff as soon as possible.

Thanks! :-)

**Comment by simonask** [comment]
Alright, I ported the build-related things to the `version-2` branch (#10). I would still appreciate the other fixes in a separate PR, or even better if you have time to rebase this on top of #10 (but that might be a bit of work).

**Comment by Kijewski** [comment]
Everything but some possible noexcept problems as not either in #10 or #4.

I'd leave reviewing where to use `noexcept`, where not, and where to use something as ugly `noexcept(std::is_nothrow_move_assignable_v<R>)` for some other time.

**Comment by simonask** [comment]
Yeah I agree, I've punted on adding conditional `noexcept` in general since it tends to really complicate things.

I really wish `std::bad_alloc` was not a thing.

**Pull request closed without merging**
